### ISSUE TITLE
Add 2 missing PDFs for 2 case studies

### ISSUE THREAD

**Issue by neektza** [floatingpointio/natureforpeople.org#71]

**Comment by elkarrde** [comment]
Err, these files are not missing. Both are already up-and-running.

**Comment by elkarrde** [comment]
[Obedska bara - PZZP **BCS PDF**](https://github.com/floatingpointio/natureforpeople.org/files/1995894/Obedska.bara.-.PZZP.pdf), [BCS web](https://natureforpeople.org/articles/en-evolucija-u-restauraciji-i-ocuvanju-travnih-stanita-obedska-bara/case-study/)

**Comment by elkarrde** [comment]
[Stepski sokol - DZPPS_eng **EN PDF**](https://github.com/floatingpointio/natureforpeople.org/files/1995899/Stepski.sokol.-.DZPPS_eng.pdf), [EN web](https://natureforpeople.org/articles/cooperation-with-the-electric-company-to-improve-protection-of-the-saker-falcon/case-study/)
